<?php

namespace AppBundle\Repository;

/**
 * UtilisateurAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurAdresseRepository extends \Doctrine\ORM\EntityRepository
{
}
