app:
    resource: '@AppBundle/Controller/'
    type: annotation
 

page:
    resource: "@PageBundle/Controller/"
    type:     annotation

    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"